name: 'Update Feature Badge'
description: 'Update the feature badge in the given file. The badge indicates how many features production is behind staging.'

inputs:
  method:
    description: 'Define if the feature difference count should be increased or reset to 0. Choose between "increase" or "reset".'
    required: false
    default: 'increase'

  file_path:
    description: 'Path to the file that holds the feature badge.'
    required: false
    default: 'README.md'

  project_name:
    description: 'Name of the project using this action.'
    requird: true

runs:
  using: 'composite'
  steps:
  - name: Checkout
    uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.10'

  - name: Update badge
    shell: bash
    run: python update_feature_badge.py ${{ inputs.method }} ${{ inputs.file_path }} ${{ inputs.project_name }}

  - name: Commit and push
    shell: bash
    run: |
      git config --global user.name "GitHub Actions"
      git config --global user.email "actions@github.com"
      git add ${{ inputs.file_path }}
      git commit -m "Update feature diff badge" || echo "No changes to commit"
      git push || echo "No changes to commit"
